language: c

dist: xenial

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential
  - sudo apt-get install -qq gcc-arm-none-eabi
  - sudo apt-get install -qq libnewlib-arm-none-eabi
  - sudo apt-get install -qq gcc-avr avr-libc binutils-avr
  - sudo apt-get install -qq mingw-w64

compiler:
  - gcc

jobs:
  - include:
    - stage: demos-build
      os: linux
      compiler: gcc
      script: make clean all
    - stage: gateway-build
      os: linux
      compiler: gcc
      script: make clean gateway
    - stage: ports-arm
      os: linux
      before_script:
        - arm-none-eabi-gcc --version
      script:
        - make stm32f10x
        - make at91sam7s
    - stage: ports-avr
      os: linux
      before_script:
        - avr-gcc --version
      script:
        - make atmega168
        - make bdk-atxx4-mstp
